services:
  mongo:
    image: mongo
    container_name: mongoDB
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_URL=mongodb://user:password@mongo:27017/
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password


volumes:
  mongo: {}
